# Stage 1: Base image
FROM node:latest as base
WORKDIR /app
RUN npm install -g @angular/cli

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy Angular app files
COPY . .

# Create nginx user
RUN adduser --disabled-password --shell /bin/bash --gecos '' nginx

# Change ownership of files to nginx user
RUN chown -R nginx:nginx /app

# Install Node.js in production image
RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs

# Build Angular app
RUN ng build --configuration=production --base-href=/fig-angular/

# Stage 2: Production image
FROM nginx:latest

# Create necessary directories
RUN mkdir -p /var/cache/nginx/client_temp

# Copy nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy Angular app files from previous stage
COPY --from=base /app/dist/fig-angular /usr/share/nginx/html/fig-angular

# Change ownership of files to nginx user
RUN chown -R nginx:nginx /usr/share/nginx/html/fig-angular

# Start Nginx server
CMD ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
